<?php
/**
 * Created by PhpStorm.
 * User: ruanxinwu
 * Date: 2019/3/6
 * Time: 11:39
 */
namespace app\modules\admin;

class Module extends \Yii\base\Module
{
    public $controllerNamespace = 'app\modules\admin\controllers';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}