<?php
/**
 * Created by PhpStorm.
 * User: ruanxinwu
 * Date: 2019/3/6
 * Time: 11:43
 */
namespace app\modules\user\controllers;

use app\models\db\SailCompany;
use app\modules\user\services\TestService;
use Codeception\Module\Redis;
use dede\abc;
use dede\sss;
use yii\base\Security;
use yii\filters\AccessControl;
use yii\web\Controller;

class IndexController extends Controller
{
    public $shop;

    public function behaviorsz()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ],

            ]
        ];
    }

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        pd_var(ini_get('display_errors'),gethostname(),$_SERVER['SERVER_NAME'],$_SERVER['HTTP_HOST'],$_SERVER['REQUEST_URI']);
        pd_var(\Yii::$app->user->identity);
    }


    public function demo()
    {
        $pages = [
            'cart' => '购物车页',
            'category' => '分类页',
            'error' => '异常页',
            'index' => '首页',
            'order' => '订单页',
            'product-detail' => '商品详情页',
            'product-lists' => '商品列表页',
            'result' => '结果页',
            'search' => '搜索页',
        ];

        $modules = [
            'category' => '商品分类',
            'collection' => '精选商品',
            'text' => '文本',
            'subscribe' => '订阅',
            'single-product' => '单个商品',
            'single-image' => '单图',
            'pages-collections' => '商品列表页',
            'pages-product' => '商品详情页',
            'pages-categories' => '分类页',
            'cart' => '购物车页',
            'order' => '订单页',
            'result' => '结果页',
            'search' => '搜索页',
            'error' => '异常页'
        ];

        //$file  = new \CURLFile('https://hn-img-mall-1.oss-cn-shenzhen.aliyuncs.com/uploader/d0bec1c55aa94714ca44e65b74af5dfc9b6d4a85.png','application/octet-stream');
        header('Content-type:text/html; charset=utf-8'); //声明编码
        $ch = curl_init();
        $file = 'https://hn-img-mall-1.oss-cn-shenzhen.aliyuncs.com/uploader/d0bec1c55aa94714ca44e65b74af5dfc9b6d4a85.png';
        $aaa = file_get_contents($file);
        file_put_contents('/tmp/85.png',$aaa);
        $local = \Yii::$app->request->getHostInfo() . '/sail/upload/file' ;
        $file = '/tmp/85.png';
        $curlPost = array('sd' => 'weeee','file' => new \CURLFile($file));
        // pd($curlPost);
        curl_setopt($ch, CURLOPT_URL, $local);
        curl_setopt($ch, CURLOPT_HEADER, 0);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 0);
        //curl_setopt($ch, CURLOPT_SAFE_UPLOAD, false);
//        curl_setopt($ch, CURLOPT_REFERER, "http://www.baidu.com");
        curl_setopt($ch, CURLOPT_POST, true); //POST提交
        curl_setopt($ch, CURLOPT_POSTFIELDS,$curlPost);
        curl_exec($ch);
        curl_close($ch);
    }


}